const en = {
  i18n_titulo: 'HEPA filters calculator',
  i18n_enlace__calculadora: 'Calculator',
  i18n_enlace__informacion: 'Information',
  i18n_introduccion: 'Enter the classroom dimensions (length, width and height) in meters from floor to ceiling, along with the number of air changes you want *.',
  i18n_largo: 'Length (m)',
  i18n_ancho: 'Width (m)',
  i18n_altura: 'Height (m)',
  i18n_cambio__aire: 'Air changes you want',
  i18n_cambio__aireInf: 'Harvard recommendation is 5 <br /> (better to leave it at 5)',
  i18n_ventilacion__normativa: 'Select the level of classroom ventilation and current country regulations',
  i18n_ventilacion: 'Ventilation',
  i18n_ventilacion__0: 'Poor ventilation',
  i18n_ventilacion__1: 'Low ventilation',
  i18n_ventilacion__2: 'Normal',
  i18n_ventilacion__3: 'Good ventilation (complies with RITE)',
  i18n_ventilacion__4: 'Improved ventilation with some system',
  i18n_ventilacion__inf0: 'Select this option if your school has poor ventilation.',
  i18n_ventilacion__inf1: 'Select this option if your school has low ventilation or if you are unsure (as a reference, a home in the USA typically has 0.5 CAH).',
  i18n_ventilacion__inf2: 'This is an approximation of the average rate of air change in many schools, based on research studies.',
  i18n_ventilacion__inf3: 'This is an approximation of the minimum rate of air change that should be in schools by default, but most do not reach this value.',
  i18n_ventilacion__inf4: 'Select this option only if your school has made improvements beyond the minimum requirements.',
  i18n_normativa: 'Normative',
  i18n_normativa__0: 'American normative',
  i18n_CADR__m3h: 'CADR (m<sup>3</sup>/h)',
  i18n_CADR__m3hInf_0: 'Clean Air Delivery Rate.',
  i18n_CADR__m3hInf_1: 'Filters (individual or multiple, must add this together).',
  i18n_CADR__cfm: 'CADR (cfm)***',
  i18n_CADR__cfmInf_0: '*** Cubit feet per minute',
  i18n_CADR__cfmInf_1: 'CADR in cfm, for filters that bring only that unit.',
  i18n_subtitulo: 'CO2 limit that the meter cannot exceed',
  i18n_subtituloInf: 'CO2 Generation Rate',
  i18n_numero__estudiantes: 'Number of students',
  i18n_numero__profesores: 'Number of <br /> teachers',
  i18n_calibracion__co2: 'External CO2 calibration',
  i18n_limite__co2_sin__HEPA: 'CO2 limit that the meter cannot exceed if you do NOT use a HEPA filter (ppm)',
  i18n_limite__co2_con__HEPA: 'CO2 limit that the meter cannot exceed if you use a HEPA filter * (ppm)',
  i18n_limite__c02Inf_0: '* It is not desirable for the ppm <sup> ** </sup> to exceed the above rate in any situation, but in extreme cold the virus and aerosols would be eliminated and those ppm could be reached',
  i18n_limite__c02Inf_1: '** Parts per million',
  i18n_sobre__calculadora: 'About the Calculator',
  i18n_sobre__calculadora_parrafo_1: 'Adaptation of the original calculator created by:',
  i18n_sobre__calculadora_parrafo_2: 'of the Harvard T.H. Chan Y',
  i18n_sobre__calculadora_parrafo_3: 'and the University of Colorado Boulder:',
  i18n_sobre__calculadora_parrafo_4: 'Read all the scientific assumptions on the calculator\'s ReadMe page.',
  i18n_antes__empezar: 'Before you start, read this:',
  i18n_antes__empezar_parrafo_1: 'Frequently asked questions about how to protect yourself from COVID-19 aerosol transmission (see section 9 for Air Filtering and Cleaning)',
  i18n_antes__empezar_parrafo_2: 'Thread about HEPA filters and other alternative filtration systems written by Jos&eacute; Luis Jim&eacute;nez (world aerosol expert), translated and expanded by Pablo Fuentes:',
  i18n_antes__empezar_parrafo_3: 'Thread about Hoaxes on HEPA filters written by Jos&eacute; Luis Jim&eacute;nez (world aerosol expert):',
  i18n_tres__cosas: '3 things to keep in mind when buying a HEPA filter that is effective against SARS-CoV-2',
  i18n_tres__cosas_parrafo_1: 'That complies with EN 1822-1: 2009 (see below)',
  i18n_tres__cosas_parrafo_2: 'Ensure that they are filters H13 or higher: retention efficiency 99.95% or higher: H14, U15, U16 (being strict, the HEPA filter only includes two degrees of classification: H13 99.95% MPPS and H14 99.995% MPPS)',
  i18n_tres__cosas_parrafo_3: 'Ensure that it is adapted to the space where we are going to use it (use CADR rate calculator)',
  i18n_informacion__adicional: 'Additional Information',
  i18n_garantia__filtros: 'Ensure the quality of HEPA and ULPA filters',
  i18n_garantia__filtros_parrafo_1: 'The European filter test standard EN 1822-1: 2009 is the most important base for testing and classifying absolute filters. The standard is based on state-of-the-art particle measurement technology and authorized procedures for determining energy efficiency. It consists of five parts. The filter is assigned the corresponding filter class using the results of Sections 4 (local efficiency) and 5 (integral efficiency).',
  i18n_garantia__filtros_parrafo_2: 'An individual test report and a serial number are generated for filters of classes H13 and higher. Therefore, each filter from H13 can be assigned its individual test.',
  i18n_parte__1: 'Part 1: Classification, Performance, Testing, and Identification',
  i18n_parte__1_parrafo_1: 'EN 1822-1: 2009 establishes three groups:',
  i18n_parte__1_parrafo_2: 'Group E: EPA Filter &ndash; Efficient particulate air',
  i18n_parte__1_parrafo_3: 'Group H: HEPA Filter &ndash; High efficiency-particular air',
  i18n_parte__1_parrafo_4: 'Group U: ULPA Filter &ndash; Ultra low penetration air',
  i18n_parte__1_parrafo_5: 'Absolute filters are rated based on integral and local efficiency values that are determined during testing.',
  i18n_parte__2: 'Part 2: Aerosol Production, Measurement Equipment, Particle Count Statistics',
  i18n_parte__2_parrafo_1: 'This part describes test conditions and aerosol generators, particle measurement technology, and statistical procedures to evaluate counts.',
  i18n_parte__2_parrafo_2: '* Integral efficiency is the average value of all the local efficiencies on the front area of the filter, In the first phase of this EN 1822 standard, fractional yield will be evaluated for the filter measurements ready at the same speed as the filter. The purpose is to determine the particle size which the average offers the lowest retention efficiency, called: Highest Penetration Particle Size (MPPS).',
  i18n_parte__3: 'Part 3: Flat Sheet Filter Media Test (Determines MMPS)',
  i18n_parte__3_parrafo_1: 'Part 3 describes the determination of the fractional efficiency and the determination of the most penetrating particle size (MMPS) of the flat sheet filter medium.',
  i18n_parte__3_parrafo_2: 'A test aerosol is applied to the filter medium at the specified nominal flow rate for later use of the filter. The partial flows of the test aerosol are directed up and down in the filter sample. The particle counting method determines particle concentrations and calculates the fractional efficiency curve. The particle size at which the fractional efficiency curve reaches its lowest point is called the MPPS. In simplest terms, this is the particle size with which a filter medium works worst for a defined flow rate.',
  i18n_parte__4: 'Part 4: Filter Element Leak Test (Scanner Method)',
  i18n_parte__4_parrafo_1: 'This section is about how to test if your filters are not leaking. Leaks can occur due to filter medium failure, improper seal between pleat assembly and frame, or component handling irregularities. Due to the high filtration efficiency estimated for absolute filters, even the smallest leak (only visible to the human eye) can produce higher concentrations of local particles.',
  i18n_parte__4_parrafo_2: 'For the automated process (scanner test), the filter element is placed on a test bench and then a DEHS (di-2-ethylhexyl sebacate) test aerosol is applied. The average aerosol particle size should be in the MPPS range. The flow side of the filter is approached using probes with a computer-controlled linear axis. At each point on the clean air side, local aerosol concentrations are measured to determine the degree of local penetration. If the aerosol concentration does not exceed the established limit at any point, the filter is considered not to be leaking.',
  i18n_parte__4_parrafo_3: 'The need to determine local efficiencies also implies the need to carry out individual tests for each filter element of filter classes above H13.',
  i18n_parte__5: 'Part 5: Determining the efficiency of filter elements',
  i18n_parte__5_parrafo_1: 'Part 5 describes the determination of the integral filter efficiency. This value is usually calculated as the average of the individual local efficiencies included in part 4. Alternatively, individual measurement with fixed sampling probes is also allowed.'
}