const es = {
  i18n_titulo: 'Calculadora filtros HEPA',
  i18n_enlace__calculadora: 'Calculadora',
  i18n_enlace__informacion: 'Informaci&oacute;n',
  i18n_introduccion: 'Introduzca las dimensiones del aula largo, ancho y la altura en metros desde el suelo al techo, junto con el n&uacute;mero de cambios de aire que desea*.',
  i18n_largo: 'Largo (m)',
  i18n_ancho: 'Ancho (m)',
  i18n_altura: 'Altura (m)',
  i18n_cambio__aire: 'Cambios de aire que desea',
  i18n_cambio__aireInf: 'Recomendaci&oacute;n Harvard es 5 <br /> (mejor dejarlo en 5)',
  i18n_ventilacion__normativa: 'Seleccione el nivel de ventilaci&oacute;n del aula y la normativa vigente del pa&iacute;s.',
  i18n_ventilacion: 'Ventilaci&oacute;n',
  i18n_ventilacion__0: 'Mala ventilaci&oacute;n',
  i18n_ventilacion__1: 'Ventilaci&oacute;n baja',
  i18n_ventilacion__2: 'Normal',
  i18n_ventilacion__3: 'Buena ventilaci&oacute;n (cumple con RITE)',
  i18n_ventilacion__4: 'Ventilaci&oacute;n mejorada con alg&uacute;n sistema',
  i18n_ventilacion__inf0: 'Selecciones esta opci&oacute;n si su escuela tiene mala ventilaci&oacute;n.',
  i18n_ventilacion__inf1: 'Seleccione esta opci&oacute;n si su escuela tiene baja ventilaci&oacute;n o si no est&aacute; seguro/a (como referencia, una casa en EEUU tiene 0.5 CAH tipicamente).',
  i18n_ventilacion__inf2: 'Esta es una aproximaci&oacute;n de la tasa promedio de cambio de aire en muchas escuelas, basada en estudios de investigaci&oacute;n.',
  i18n_ventilacion__inf3: 'Esta es una aproximaci&oacute;n de la m&iacute;nima tasa de cambio de aire que deber&iacute;a estar en las escuelas por dise&ntilde;o, pero la mayor&iacute;a no logra alcanzar este valor.',
  i18n_ventilacion__inf4: 'Seleccione esta opci&oacute;n solo si su escuela ha realizado mejor&iacute;as mas all&aacute; de los requisitos m&iacute;nimos.',
  i18n_normativa: 'Normativa',
  i18n_normativa__0: 'Normativa americana',
  i18n_CADR__m3h: 'CADR (m<sup>3</sup>/h)',
  i18n_CADR__m3hInf_0: 'Clean Air Delivery Rate (Tasas de entrega de aire limpio).',
  i18n_CADR__m3hInf_1: 'Los filtros (individual o varios, deben sumar esto).',
  i18n_CADR__cfm: 'CADR (cfm)***',
  i18n_CADR__cfmInf_0: '*** Pies c&uacute;bicos por minuto',
  i18n_CADR__cfmInf_1: 'CADR en cfm, para filtros que traigan solo esa unidad.',
  i18n_subtitulo: 'L&iacute;mite CO2 que no puede superar el medidor',
  i18n_subtituloInf: 'Tasa de Generaci&oacute;n de CO2',
  i18n_numero__estudiantes: 'N&uacute;mero de estudiantes',
  i18n_numero__profesores: 'N&uacute;mero de profesores',
  i18n_calibracion__co2: 'Calibraci&oacute;n CO2 exterior',
  i18n_limite__co2_sin__HEPA: 'L&iacute;mite CO2 que no puede superar el medidor si NO usa filtro HEPA (ppm)',
  i18n_limite__co2_con__HEPA: 'L&iacute;mite CO2 que no puede superar el medidor si usa filtro HEPA* (ppm)',
  i18n_limite__c02Inf_0: '* No es deseable que los ppm<sup>**</sup> superen la tasa de arriba en ning&uacute;n caso, pero en caso extremo de fr&iacute;o se estar&iacute;an eliminando el virus y los aerosoles y se podr&iacute;a llegar a esos ppm',
  i18n_limite__c02Inf_1: '** Partes por mill&oacute;n',
  i18n_sobre__calculadora: 'Sobre la Calculadora',
  i18n_sobre__calculadora_parrafo_1: 'Adaptaci&oacute;n de la calculadora original creada por:',
  i18n_sobre__calculadora_parrafo_2: 'del Instituto de Salud Publica de Harvard T.H. Chan Y',
  i18n_sobre__calculadora_parrafo_3: 'y la Universidad de Colorado Boulder:',
  i18n_sobre__calculadora_parrafo_4: 'Lea todas las asunciones cient&iacute;ficas en la p&aacute;gina ReadMe de dicha calculadora.',
  i18n_antes__empezar: 'Antes de empezar, lee esto:',
  i18n_antes__empezar_parrafo_1: 'Preguntas frecuentes sobre c&oacute;mo protegerse de la transmisi&oacute;n de aerosol COVID-19 (ver secci&oacute;n 9 para Filtrado y Limpieza de Aire)',
  i18n_antes__empezar_parrafo_2: 'Hilo sobre filtros HEPA y otros sistemas alternativos de filtrados escrito por Jos&eacute; Luis Jim&eacute;nez (experto mundial en aerosoles), traducido y ampliado por Pablo Fuente:',
  i18n_antes__empezar_parrafo_3: 'Hilo sobre Bulos sobre los filtros HEPA escrito por Jos&eacute; Luis Jim&eacute;nez (experto mundial en aerosoles):',
  i18n_tres__cosas: '3 cosas que debemos tener en cuenta a la hora de comprar un filtro HEPA que sea eficaz contra el SARS-CoV-2',
  i18n_tres__cosas_parrafo_1: 'Que cumpla la normativa EN 1822-1:2009 (ver abajo)',
  i18n_tres__cosas_parrafo_2: 'Que sean filtros H13 o superiores: eficacia de retenci&oacute;n 99,95% o superior: H14, U15, U16 (siendo estrictos, el filtro HEPA solo incluye dos grados de clasificaci&oacute;n: H13 99,95% MPPS y H14 99,995% MPPS)',
  i18n_tres__cosas_parrafo_3: 'Que se adec&uacute;e al espacio donde lo vayamos a utilizar (utilizar calculadora tasa CADR)',
  i18n_informacion__adicional: 'Informaci&oacute;n Adicional',
  i18n_garantia__filtros: 'Garantizar la calidad de los filtros HEPA y ULPA',
  i18n_garantia__filtros_parrafo_1: 'La normativa EN 1822-1:2009 de prueba de filtro europea es la base m&aacute;s importante para probar y clasificar los filtros absolutos. La norma se basa en la vanguardista tecnolog&iacute;a de medici&oacute;n de part&iacute;culas y en los procedimientos autorizados para determinar la eficiencia energ&eacute;tica. Consta de cinco partes. Al filtro se le asigna la clase de filtro correspondiente empleando los resultados de las secciones 4 (eficacia local) y 5 (eficacia integral).',
  i18n_garantia__filtros_parrafo_2: 'Se generan un informe de prueba individual y un n&uacute;mero de serie para los filtros de las clases H13 y superiores. Por lo tanto, se puede asignar a cada filtro a partir de H13 su prueba individual.',
  i18n_parte__1: 'Parte 1: Clasificaci&oacute;n, rendimiento, prueba e identificaci&oacute;n',
  i18n_parte__1_parrafo_1: 'La EN 1822-1:2009 establece tres grupos:',
  i18n_parte__1_parrafo_2: 'Grupo E: Filtro EPA &ndash; Efficient particulate air',
  i18n_parte__1_parrafo_3: 'Grupo H: Filtro HEPA &ndash; High efficiency-particular air',
  i18n_parte__1_parrafo_4: 'Grupo U: Filtro ULPA &ndash; Ultra low penetration air',
  i18n_parte__1_parrafo_5: 'Los filtros absolutos se clasifican seg&uacute;n los valores de eficacia locales e integrales que se determinan durante la prueba.',
  i18n_parte__2: 'Parte 2: Producci&oacute;n de aerosol, equipo de medici&oacute;n, estad&iacute;sticas de recuento de part&iacute;culas',
  i18n_parte__2_parrafo_1: 'Esta parte describe las condiciones de prueba y los generadores de aerosol, la tecnolog&iacute;a de medici&oacute;n de part&iacute;culas y los procedimientos estad&iacute;sticos para evaluar los recuentos.',
  i18n_parte__2_parrafo_2: '* La eficacia integral es el valor medio de todas las eficacias locales sobre el &aacute;rea frontal del filtro.En la primera fase de esta norma EN 1822 se evaluar&aacute; el rendimiento fraccionario para las medidas de filtraci&oacute;n listas a la misma velocidad que en el filtro. El prop&oacute;sito es determinar el tama&ntilde;o de part&iacute;culas a la cual la media ofrece la eficacia de retenci&oacute;n m&aacute;s baja que se denomina: Tama&ntilde;o de Part&iacute;cula de Mayor Penetraci&oacute;n (MPPS).',
  i18n_parte__3: 'Parte 3: Prueba del medio filtrante de l&aacute;mina plana (determina el MMPS)',
  i18n_parte__3_parrafo_1: 'La parte 3 describe la determinaci&oacute;n de la eficiencia fraccional y la determinaci&oacute;n del tama&ntilde;o de part&iacute;cula m&aacute;s penetrante (MMPS) del medio filtrante de l&aacute;mina plana.',
  i18n_parte__3_parrafo_2: 'Se aplica un aerosol de prueba al medio filtrante a la velocidad de flujo nominal especificada para el uso posterior del filtro. Los flujos parciales del aerosol de prueba se dirigen hacia arriba y hacia abajo en la muestra del filtro. El m&eacute;todo de recuento de part&iacute;culas determina las concentraciones de part&iacute;culas y calcula la curva de eficiencia fraccional. El tama&ntilde;o de part&iacute;cula en el que la curva de eficiencia fraccional alcanza su punto m&aacute;s bajo se llama el MPPS. En t&eacute;rminos m&aacute;s sencillos, este es el tama&ntilde;o de part&iacute;cula con el que un medio filtrante trabaja peor para una velocidad de flujo definida.',
  i18n_parte__4: 'Parte 4: Prueba de fugas de elementos del filtro (m&eacute;todo de esc&aacute;ner)',
  i18n_parte__4_parrafo_1: 'Esta secci&oacute;n trata sobre c&oacute;mo probar que los filtros no tienen fugas. Pueden producirse fugas debido a fallas en el medio filtrante, a un sellado inadecuado entre el conjunto de pliegues y el marco o a irregularidades en el manejo de los componentes. Debido a la elevada eficiencia de filtraci&oacute;n estimada para los filtros absolutos, incluso la m&aacute;s m&iacute;nima fuga (apenas visible para el ojo humano) puede producir mayores concentraciones de part&iacute;culas locales.',
  i18n_parte__4_parrafo_2: 'Para el proceso automatizado (prueba de esc&aacute;ner), el elemento filtrante se coloca en un banco de ensayos y luego se aplica un aerosol de prueba de DEHS (di-2-etilhexil sebacato). El tama&ntilde;o medio de la part&iacute;cula del aerosol debe estar en el rango del MPPS. La aproximaci&oacute;n del lado del flujo del filtro se realiza empleando sondas con un eje lineal controlado por ordenador. En cada punto del lado del aire limpio se miden las concentraciones locales de aerosol para fijar el grado de penetraci&oacute;n local. Si la concentraci&oacute;n de aerosol no supera el l&iacute;mite establecido en ning&uacute;n punto, se considera que el filtro no presenta fugas.',
  i18n_parte__4_parrafo_3: 'La necesidad de determinar las eficiencias locales tambi&eacute;n implica la necesidad de realizar pruebas individuales para cada elemento del filtro de las clases de filtro superiores a H13.',
  i18n_parte__5: 'Parte 5: Determinaci&oacute;n de la eficiencia de los elementos del filtro',
  i18n_parte__5_parrafo_1: 'La parte 5 describe la determinaci&oacute;n de la eficiencia del filtro integral. Este valor suele calcularse como la media de las eficiencias individuales locales que se han medido en la parte 4. De manera alternativa, tambi&eacute;n se permite una medici&oacute;n individual con sondas de muestreo fijas.'
}