const pt = {
  i18n_titulo: 'Calculadora filtros HEPA',
  i18n_enlace__calculadora: 'Calculadora',
  i18n_enlace__informacion: 'Informa&ccedil;&atildeo',
  i18n_introduccion: 'Introduza as dimens&otilde;es de sala de aula (largura, comprimento e altura) em metros desde o ch&atilde;o at&eacute; ao teto, juntamente com o n&uacute;mero de mudanças de ar que deseja*.',
  i18n_largo: 'Comprimento (m)',
  i18n_ancho: 'Largura (m)',
  i18n_altura: 'Altura (m)',
  i18n_cambio__aire: 'Mudanças de ar que deseja',
  i18n_cambio__aireInf: 'Recomenda&ccedil;&atilde;o Harvard &eacute; 5 <br /> (&eacute; melhor deixar em 5)',
  i18n_ventilacion__normativa: 'Selecionar o nivel de ventila&ccedil;&atilde;o da sala de aula e a normativa vigente do pa&iacute;s.',
  i18n_ventilacion: 'Ventila&ccedil;&atilde;o',
  i18n_ventilacion__0: 'M&aacute; ventila&ccedil;&atilde;o',
  i18n_ventilacion__1: 'Ventila&ccedil;&atilde;o baixa',
  i18n_ventilacion__2: 'Normal',
  i18n_ventilacion__3: 'Boa ventila&ccedil;&atilde;o (cumpre com RITE)',
  i18n_ventilacion__4: 'Ventila&ccedil;&atilde;o melhorada com algum sistema',
  i18n_ventilacion__inf0: 'Selecionar esta op&ccedil;&atilde;o se a sua escola tem m&aacute; ventila&ccedil;&atilde;o',
  i18n_ventilacion__inf1: 'Selecionar esta op&ccedil;&atilde;o se a sua escola tem baixa ventila&ccedil;&atilde;o ou se n&atilde;o tem a certeza (como refer&ecirc;ncia, uma casa nos EUA tem 0.5 CAH normalmente).',
  i18n_ventilacion__inf2: 'Esta &eacute; uma aproxima&ccedil;&atilde;o da taxa m&eacute;dia de mudan&ccedil;a de ar em muitas escolas, baseada em estudos de investiga&ccedil;&atilde;o.',
  i18n_ventilacion__inf3: 'Esta &eacute; uma aproxima&ccedil;&atilde;o da taxa m&iacute;nima de mudan&ccedil;a de ar que deveria estar nas escolas por defeito, mas a maioria n&atilde;o chega a alcan&ccedil;ar esse valor.',
  i18n_ventilacion__inf4: 'Selecionar esta opci&ccedil;&atilde;o s&oacute; se a sua escola tiver realizado melhorias mais al&eacute;m dos requisitos m&iacute;nimos.',
  i18n_normativa: 'Normativa',
  i18n_normativa__0: 'Normativa americana',
  i18n_CADR__m3h: 'CADR (m<sup>3</sup>/h)',
  i18n_CADR__m3hInf_0: 'Clean Air Delivery Rate (Taxas de entrega de ar limpo).',
  i18n_CADR__m3hInf_1: 'Os filtros (individual ou v&aacute;rios, devem somar isto).',
  i18n_CADR__cfm: 'CADR (cfm)***',
  i18n_CADR__cfmInf_0: '*** P&eacute;s c&uacute;bicos por minuto',
  i18n_CADR__cfmInf_1: 'CADR em cfm, para filtros que tragam s&oacute; essa unidade.',
  i18n_subtitulo: 'Limite CO2 que n&atilde;o pode superar o medidor',
  i18n_subtituloInf: 'Taxa de Gera&ccedil;&atilde;o de CO2',
  i18n_numero__estudiantes: 'N&uacute;mero de estudantes',
  i18n_numero__profesores: 'N&uacute;mero de professores',
  i18n_calibracion__co2: 'Calibragem CO2 exterior',
  i18n_limite__co2_sin__HEPA: 'Limite CO2 que n&atilde;o pode superar o medidor se n&atilde;o usa filtro HEPA (ppm)',
  i18n_limite__co2_con__HEPA: 'Limite CO2 que n&atilde;o pode superar o medidor se usa filtro HEPA* (ppm)',
  i18n_limite__c02Inf_0: '* n&atilde;o &eacute; desej&aacute;vel que os ppm<sup>**</sup> superem a taxa de cima em nenhuma situa&ccedil;&atilde;o, mas no extremo de frio estar-se-iam a eliminar o virus e os aerosois e poder-se-ia chegar a esses ppm',
  i18n_limite__c02Inf_1: '** Partes por milh&atilde;o',
  i18n_sobre__calculadora: 'Sobre a Calculadora',
  i18n_sobre__calculadora_parrafo_1: 'Adapta&ccedil;&atilde;o da calculadora original criada por:',
  i18n_sobre__calculadora_parrafo_2: 'do Instituto de Sa&uacute;de P&uacute;blica de Harvard T.H. Chan Y',
  i18n_sobre__calculadora_parrafo_3: 'e a Universidade de Colorado Boulder:',
  i18n_sobre__calculadora_parrafo_4: 'Leia todas as suposi&ccedil;&otilde;es cient&iacute;ficas na p&aacute;gina ReadMe da calculadora.',
  i18n_antes__empezar: 'Antes de come&ccedil;ar, leia isto:',
  i18n_antes__empezar_parrafo_1: 'Perguntas frequentes sobre como se proteger da transmi&ccedil;&atilde;o de aerossol COVID-19 (ver sec&ccedil;&atilde;o 9 para Filtragem e Limpeza do Ar)',
  i18n_antes__empezar_parrafo_2: 'Discuss&atilde;o sobre filtros HEPA e outros sistemas alternativos de filtros escrito por Jos&eacute; Luis Jim&eacute;nez (especialista mundial em aeross&oacute;is), traduzido e ampliado por Pablo Fuente:',
  i18n_antes__empezar_parrafo_3: 'Discuss&atilde;o sobre not&iacute;cias falsas sobre os filtros HEPA escrito por Jos&eacute; Luis Jim&eacute;nez (especialista mundial em aeross&oacute;is):',
  i18n_tres__cosas: '3 coisas que devemos ter em conta na hora de comprar um filtro HEPA que seja eficaz contra o SARS-CoV-2',
  i18n_tres__cosas_parrafo_1: 'Que cumpra a normativa EN 1822-1:2009 (ver abaixo)',
  i18n_tres__cosas_parrafo_2: 'Que sejam filtros H13 ou superiores: efic&aacute;cia de reten&ccedil;&atilde;o 99,95% ou superior: H14, U15, U16 (sendo rigorosos, o filtro HEPA s&oacute; inclu&iacute; dois graus de clasifica&ccedil;&atilde;o: H13 99,95% MPPS e H14 99,995% MPPS)',
  i18n_tres__cosas_parrafo_3: 'Que seja adequado ao espa&ccedil;o onde o vamos utilizar (utilizar calculadora taxa CADR)',
  i18n_informacion__adicional: 'Informa&ccedil;&atilde;o Adicional',
  i18n_garantia__filtros: 'Garantir a qualidade dos filtros HEPA e ULPA',
  i18n_garantia__filtros_parrafo_1: 'A normativa EN 1822-1:2009 de prova de filtragem europeia &eacute; a base mais importante para provar e classificar os filtros absolutos. A norma baseia-se na vanguardista tecnologia de medi&ccedil;&atilde;o de part&iacute;culas e nos procedimentos autorizados para determinar a efici&ecirc;ncia energ&eacute;tica. Tem cinco partes. &Eacute; atribuida ao filtro a classe de filragem correspondente, aplicando os resultados das sec&ccedil;&otilde;es 4 (efic&aacute;cia local) e 5 (efic&aacute;cia integral).',
  i18n_garantia__filtros_parrafo_2: 'S&atilde;o gerados um relat&oacute;rio de prova individual e um n&uacute;mero de serie para os filtros das classes H13 e superiores. Assim, pode-se atribuir a cada filtro a partir de H13 a sua prova individual.',
  i18n_parte__1: 'Parte 1: Clasifica&ccedil;&atilde;o, rendimento, prova e identifica&ccedil;&atilde;o',
  i18n_parte__1_parrafo_1: 'A EN 1822-1:2009 estabelece tr&ecirc;s grupos:',
  i18n_parte__1_parrafo_2: 'Grupo E: Filtro EPA &ndash; Efficient particulate air',
  i18n_parte__1_parrafo_3: 'Grupo H: Filtro HEPA &ndash; High efficiency-particular air',
  i18n_parte__1_parrafo_4: 'Grupo U: Filtro ULPA &ndash; Ultra low penetration air',
  i18n_parte__1_parrafo_5: 'os filtros absolutos classificam-se segundo os valores de efic&aacute;cia locais e integrais que se determinam durante a prova.',
  i18n_parte__2: 'Parte 2: Produc&ccedil;&atilde;o de aerossol, equipamento de medi&ccedil;&atilde;o, estat&iacute;sticas de contagem de part&iacute;culas',
  i18n_parte__2_parrafo_1: 'Esta parte descreve as condi&ccedil;&otilde;es de prova e os geradores de aerossol, a tecnologia de medi&ccedil;&atilde;o de part&iacute;culas e os procedimentos estat&iacute;sticos para avaliar as contagens.',
  i18n_parte__2_parrafo_2: '* A efic&aacute;cia integral &eacute; o valor m&eacute;dio de todas as efic&aacute;cias locais sobre a &aacute;rea frontal do filtro. Na primeira fase desta norma EN 1822 ser&aacute; avaliado o rendimento fracion&aacute;rio para as medidas de filtra&ccedil;&atilde;o prontas &agrave; mesma velocidade do filtro. O objectivo &eacute; determinar o tamanho de part&iacute;culas às quais a m&eacute;dia oferece a efic&aacute;cia de reten&ccedil;&atilde;o mais baixa que se denomina: Tamanho de Part&iacute;cula de Maior Penetra&ccedil;&atilde;o (MPPS).',
  i18n_parte__3: 'Parte 3: Prova do meio de filtragem de l&acirc;mina plana (determina o MMPS)',
  i18n_parte__3_parrafo_1: 'A parte 3 descreve a determina&ccedil;&atilde;o da efici&ecirc;ncia fracional e a determina&ccedil;&atilde;o do tamanho de part&iacute;cula mais penetrante (MMPS) do meio de filtragem de l&acirc;mina plana.',
  i18n_parte__3_parrafo_2: 'Aplica-se um aerossol de prova ao meio de filtragem à velocidade do fluxo nominal, especificada para o uso posterior do filtro. Os fluxos parciais do aerossol de prova dirigem-se para cima e para baixo na amostra do filtro. O m&eacute;todo de contagem de part&iacute;culas determina as concentra&ccedil;&otilde;es de part&iacute;culas e calcula a curva de efici&ecirc;ncia fracional. O tamanho de part&iacute;cula no qual a curva de efici&ecirc;ncia fracional alcan&ccedil;a o seu ponto mais baixo chama-se o MPPS. Em termos mais simples, este &eacute; o tamanho de part&iacute;cula com o qual um meio de filtragem trabalha pior para uma velocidade de fluxo definida.',
  i18n_parte__4: 'Parte 4: Prova de fugas de elementos do filtro (m&eacute;todo de scanner)',
  i18n_parte__4_parrafo_1: 'Esta sec&ccedil;&atilde;o serve para provar que os filtros n&atilde;o t&ecirc;m fugas. Podem produzir-se fugas devido a falhas no meio de filtragem, à selagem inadequada entre o conjunto de dobras e o marco ou a irregularidades no manuseamento dos componentes. Devido à elevada efici&ecirc;ncia de filtra&ccedil;&atilde;o estimada para os filtros absolutos, mesmo a mais pequena fuga (apenas visiv&eacute;l ao olho humano) pode produzir maiores concentra&ccedil;&otilde;es de part&iacute;culas locais.',
  i18n_parte__4_parrafo_2: 'Para o processo automatizado (prova de scanner), o elemento filtrante coloca-se num banco de testes e de seguida aplica-se un aerossol de prova de DEHS (di-2-etilhexil sebacato). O tamanho m&eacute;dio da part&iacute;cula do aerossol deve estar no intervalo do MPPS. A aproxima&ccedil;&atilde;o do lado do fluxo do filtro faz-se aplicando sondas com um eixo linear controlado por computador. Em cada ponto do lado do ar limpo medem-se as concentra&ccedil;&otilde;es locais de aerossol para fixar o grau de penetra&ccedil;&atilde;o local. Se a concentra&ccedil;&atilde;o de aerossol n&atilde;o supera o limite estabelecido em nenhum ponto, considera-se que o filtro n&atilde;o apresenta fugas.',
  i18n_parte__4_parrafo_3: 'A necessidade de determinar as efici&ecirc;ncias locais tamb&eacute;m implica a necessidade de realizar provas individuais para cada elemento do filtro das classes de filtro superiores a H13.',
  i18n_parte__5: 'Parte 5: Determina&ccedil;&atilde;o da efici&ecirc;ncia dos elementos do filtro',
  i18n_parte__5_parrafo_1: 'A parte 5 descreve a determina&ccedil;&atilde;o da efici&ecirc;ncia do filtro integral. Este valor costuma calcular-se como a m&eacute;dia das efici&ecirc;ncias individuais locais que se incluiram na parte 4. Em alternativa, tamb&eacute;n &eacute; permitida uma medi&ccedil;&atilde;o individual com sondas de amostras fixas.'
}